project:
  type: website
  resources:
   - assets/*

website:
  title: "Open Science Workflow Training for ISC"
  reader-mode: true
  site-url: "https://moshima-pifsc.github.io/ISC_OSworkflow_training" 
  repo-url: "https://github.com/MOshima-PIFSC/ISC_OSworkflow_training"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/MOshima-PIFSC/ISC_OSworkflow_training
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Day 1"
        href: assets/day-1.html
        contents:
          - text: "Github for Collaborative Workflows"
            file: assets/day-1-pres-github_basics.qmd
          - text: "Codespaces"
            file: assets/day-1-pres-codespaces.qmd
          - text: "Reproducible environments"
            file: assets/day-1-pres-reproducible_environments.qmd
          - text: "Modifying Stock Synthesis files"
            file: assets/day-1-pres-modify-stock-synthesis.qmd
          - text: "Modifying Stock Synthesis files: Part 2"
            file: assets/day-1-pres-modify-stock-synthesis_BILLWG.qmd
      - section: "Day 2"
        href: assets/day-2.html
        contents:
          - text: "Pull requests & code review"
            file: assets/day-2-pres-PR-code-review.qmd
          - text: "Building a Shiny app"
            file: assets/day-2-pres-build-shiny.qmd
      - section: "Day 3"
        href: assets/day-3.html
        contents:
          - text: "Quarto: Reports and presentations"
            file: assets/day-3-pres-quarto.qmd
      - section: "Group projects"
        contents:
        - text: "Report template"
          file: assets/day-3-report-template.qmd
      - section: "Contact us"
        contents:
        - text: "Nicholas Ducharme-Barth"
          file: assets/web-about-nd.qmd
        - text: "Megumi Oshima"
          file: assets/web-about-mo.qmd
        - text: "Michelle Sculley"
          file: assets/web-about-ms.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/MOshima-PIFSC/ISC_OSworkflow_training/issues/new/choose

format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
      - assets/customizations/website-custom.scss
